[package]
name = "scyrox-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.58", features = ["derive"] }
hidapi = "2.6.4"
hidparser = "1.0.3"
thiserror = "2.0.18"

[profile.release]
strip = true
